# config/settings.toml

[project]
name = "etl-mini (Nítida)"
version = "0.4.0"

[paths]
db_path = "data/warehouse.duckdb"
reports_dir = "data/reports"
parquet_dir = "data/parquet"

[runner]
fail_fast = true
dq_report = "html"        # "html" | "json" | "both"
