# config/sources.yml

defaults:
  db_path: "data/warehouse.duckdb"
  mode: "replace"        # default load mode; sources can override
  group: "daily"

groups:
  daily:
    # 1) World Bank — Población total España (incremental por año)
    - name: wb_esp_pop
      type: http_json
      table: wb_esp_sp_pop_totl
      mode: incremental
      params:
        url: "https://api.worldbank.org/v2/country/ESP/indicator/SP.POP.TOTL"
        query:
          format: "json"
          per_page: 20000
        # WB devuelve [meta, data] → cogemos índice 1
        records_key_chain: ["1"]
        select: ["date", "value", "indicator", "country"]
        rename:
          date: year
        enrich:
          indicator_id: "SP.POP.TOTL"
      incremental:
        key: [year]          # dedupe por año
        cast_map:
          year: "INTEGER"
          value: "DOUBLE"

    # 2) Open-Meteo — PM2.5 últimas 7 jornadas en Madrid (incremental + export parquet particionado)
    - name: aq_madrid_pm25
      type: http_json
      table: aq_madrid_pm25
      mode: incremental
      params:
        url: "https://air-quality-api.open-meteo.com/v1/air-quality"
        query:
          latitude: 40.4168
          longitude: -3.7038
          hourly: "pm2_5"
          timezone: "UTC"
          past_days: 7
          forecast_days: 0
        # Estructura: { hourly: { time: [...], pm2_5: [...] } }
        transform: "hourly_time_value"
        transform_args:
          time_key: "time"
          value_key: "pm2_5"
          parameter: "pm25"
          unit: "µg/m³"
          latitude: 40.4168
          longitude: -3.7038
      incremental:
        key: [datetime_utc]  # clave incremental (dedupe)
        cast_map:            # TRY_CAST robusto en staging
          datetime_utc: "TIMESTAMP"
          value: "DOUBLE"
          latitude: "DOUBLE"
          longitude: "DOUBLE"
      export_parquet:
        dir: "data/parquet/aq_madrid_pm25"
        overwrite: true
        # Añadimos columnas calculadas para particionar por año/mes
        export_sql: |
          SELECT
            *,
            year(CAST(datetime_utc AS TIMESTAMP)) AS year,
            lpad(CAST(month(CAST(datetime_utc AS TIMESTAMP)) AS VARCHAR), 2, '0') AS month
          FROM aq_madrid_pm25
        partition_by: ["year", "month"]

    # 3) USGS — Terremotos últimos 7 días magnitud >= 4 (sin cambios)
    - name: usgs_quakes_7d_m40
      type: http_json
      table: usgs_quakes_7d_m40
      params:
        url: "https://earthquake.usgs.gov/fdsnws/event/1/query"
        query:
          format: "geojson"
          starttime: "@now-7d"
          endtime: "@now"
          minmagnitude: 4.0
          orderby: "time"
        records_key_chain: ["features"]
        transform: "usgs_features"   # combina properties + geometry
      post:
        cast:
          magnitude: float
          depth_km: float
